trump_quotes = ["I'm not sure I have ever asked God's forgiveness. I don't bring God into that picture....When I go to church and when I drink my little wine and have my little cracker, I guess that is a form of forgiveness. I do that as often as I can because I feel cleansed.",
"I watched when the World Trade Center came tumbling down. And I watched in Jersey City, New Jersey, where thousands and thousands of people were cheering as that building was coming down. Thousands of people were cheering.",
"(Obama) doesn't have a birth certificate. He may have one, but there's something on that, maybe religion, maybe it says he is a Muslim. I don't know. Maybe he doesn't want that.",
"An 'extremely credible source' has called my office and told me that @BarackObama's birth certificate is a fraud.",
"I am embracing the issue, and I’m proud of the issue. I think somebody has to embrace it because, frankly, the people that are – and I don’t like the name ‘birther,’ because I think it’s very unfair and I think it’s very derogatory to a lot of very good people that happen to think that there’s a possibility that this man was not born in this country, and by the way, if that were true, you know it’s very interesting, if that were true, it’d be the greatest scam in the history of this country.",
"You know, when (Ben Carson) says he went after his mother and wanted to hit her in the head with a hammer. That bothers me. I mean, that's pretty bad. I'm not saying anything other than pathological is a very serious disease. And he said he's pathological, somebody said he has pathological disease. It's in the book that he's got a pathological temper. That's a big problem because you don't cure that. You don't cure these people. You don't cure a child molester. There's no cure for it. Pathological, there's no cure for that.",
"Look at that face! Would anyone vote for that? Can you imagine that, the face of our next president?! I mean, (Carly Fiorina’s) a woman, and I'm not supposed to say bad things, but really, folks, come on. Are we serious?",
"You know, it really doesn’t matter what they write as long as you’ve got a young and beautiful piece of ass.",
"You could see there was blood coming out of (Megyn Kelly's) eyes, blood coming out of her whatever.",
"Beautiful, famous, successful, married – I’ve had them all, secretly, the world’s biggest names, but unlike Geraldo I don’t talk about it.” – From Trump’s “Think Big and Kick Ass",
"I don’t think Ivanka would do that [pose for Playboy], although she does have a very nice figure. I’ve said if Ivanka weren't my daughter, perhaps I'd be dating her.",
"The other thing with the terrorists is you have to take out their families, when you get these terrorists, you have to take out their families.",
"We’re losing a lot of people because of the Internet. We have to see Bill Gates and a lot of different people who really understand what’s happening and maybe, in some ways, closing that Internet up in some ways.",
"The Canadian plan also helps Canadians live longer and healthier than America. … We need, as a nation, to reexamine the single-payer plan, as many individual states are doing.",
"There’s many different ways (to fix health care), by the way. Everybody’s got to be covered. This is an un-Republican thing for me to say because a lot of times they say, ‘No, no, the lower 25 percent that can’t afford private.’ But...I am going to take care of everybody. I don’t care if it costs me votes or not. Everybody’s going to be taken care of much better than they’re taken care of now....the government’s gonna pay for it.",
"I identify more as a Democrat.",
"I think Bush is probably the worst President in the history of the United States.",
"Bush was a disaster for the country as well as for the Republican Party. Then he asked me about Barack Obama. I told him that Barack will need to be a great president because we’re in serious trouble as a country. It hasn’t been this way since 1929. So he doesn’t have much choice—he will simply have to be great, which he has a very good chance of being. What he has done is amazing. The fact that he accomplished what he has—in one year and against great odds—is truly phenomenal.",
"(Michael Bloomberg is) a friend of mine. He's been an excellent mayor of New York City. He's a great guy and he means very well.",
"I think pretty strongly that (Bill de Blasio will) end up being a good mayor, maybe a very good mayor and I don’t think he’s going to want to kill the golden goose. ...I think he’s a smart guy that knows what’s going on really big league and I think he is not going to want to destroy New York. I think he is going to want to make New York great.",
"(Hillary Clinton is) very talented, very smart. She's a friend of mine, so I'm a little prejudiced.",
"I know Hillary and I think she’d make a great president or vice-president.",
"We have nobody in Washington that sits back and said, you're not going to raise that fucking price.",
"No more massive injections. Tiny children are not horses—one vaccine at a time, over time.",
"An 'extremely credible source' has called my office and told me that @BarackObama's birth certificate is a fraud.",
%{I dealt with Gaddafi. I rented him a piece of land. He paid me more for one night than the land was worth for two years, and then I didn't let him use the land. That's what we should be doing. I don't want to use the word "screwed," but I screwed him. That's what we should be doing.},
"Dummy Bill Maher did an advertisement for the failing New York Times where the picture of him is very sad-he looks pathetic, bloated & gone!",
"Our country is in serious trouble. We don't have victories anymore. We used to have victories, but we don't have them. When was the last time anybody saw us beating, let's say China in a trade deal? I beat China all the time. All the time.",
"He may have one but there's something on that, maybe religion, maybe it says he is a Muslim. I don't know. Maybe he doesn't want that. Or he may not have one. I will tell you this: if he wasn't born in this country, it's one of the great scams of all time.",
"Rosie is crude, rude, obnoxious and dumb - other than that I like her very much!",
"Rosie O'Donnell's disgusting both inside and out. You take a look at her, she's a slob. She talks like a truck driver, she doesn't have her facts, she'll say anything that comes to her mind. Her show failed when it was a talk show, the ratings went very, very, very low and very bad, and she got essentially thrown off television. I mean she's basically a disaster.",
"will be releasing the full interview with a guy named Baxter @antbaxter only to show the bias and stupidity of him and @BBCWorld. Clowns!",
".@antbaxter Thanks for helping promote & make Trump International Golf Links Scotland so successful--you stupid fool!",
".@Deadspin guys are total losers—they had their story stolen right from under their bad complexions—other media capitalized!",
"Our great African American President hasn't exactly had a positive impact on the thugs who are so happily and openly destroying Baltimore!",
"Robert Pattinson should not take back Kristen Stewart. She cheated on him like a dog & will do it again--just watch. He can do much better!",
".@ariannahuff is unattractive both inside and out. I fully understand why her former husband left her for a man- he made a good decision.",
"They had no definitive proof against Tom Brady or #patriots. If Hillary doesn't have to produce Emails, why should Tom? Very unfair!",
"Stop the EBOLA patients from entering the U.S. Treat them, at the highest level, over there. THE UNITED STATES HAS ENOUGH PROBLEMS!",
"While @BetteMidler is an extremely unattractive woman, I refuse to say that because I always insist on being politically correct."]

trump_quotes.each { |quote| Quote.create(quote: quote, img: "http://i2.cdn.turner.com/cnnnext/dam/assets/150827102252-donald-trump-july-10-2015-super-169.jpg", name: "trump") }

non_trump_quotes =[ "I always was with guns, but I still hate to see what\'s happening. Now we have to protect with different things. Fully nuclear weapons. #2A",
  "I'm not going anywhere. I will bring the poorly educated back bigger and better. It's an incredible movement.  @HillaryClinton",
  "We're going to do a hell of a lot worse than waterboarding. I'll do it. When I am President is a very dark moment. @chrislhayes",
  "She required too much money out of our country. Militarily, she is a liability. Selling this country down the drain! @realDonaldTrump",
  "[Hillary] doesn't have a clue. I'm doing very well. Why hasn't she done anything about it? @HillaryClinton @realDonaldTrump #DropOutHillary",
  "It will be really easy to bring the Military into power and be very strong against the false song of globalism. @DannyEFreeman @maddow",
  "We have tremendous power over everybody. If you want to use the United States, this is the way. I'm really proud of my success. @creynoldsnc",
  "[Clinton is] running for president of hard core prison. We need a leader for America's national security interests. E-mails can't be lost.",
  "We're losing companies, the economy. We are going to save it. We're going to bring the party. Let's Make America Great Again, @MartinShkreli",
  "[A good result would be] declaring @HillaryClinton the big loser of the night. I thought it was clear, but you know, I know what I'm running",
  "I can destroy a man's life by firing him over the wall. That's always been what I'm running, to kill people and create jobs. @HillaryClinton",
  "We have to get rid of a lot of the press. I called for a temporary ban. And we really have the people's support. @Nero @AlexMarlow",
  "[Without me] you cannot have a very vicious world in four years. We're going to make it great again, folks. @AlexBWall @HillaryClinton",
  "[Birds?] Think about it. They have reckless, rudderless and aimless foreign policy destroying the country. @penningtonkm @BernieSanders",
  "Keep talking. They love me. In terms of @tedcruz, I will never have time for a second-class citizen @Maggie1715 @indystar @realDonaldTrump",
  "We don't win with healthcare, we win beating NATO and people running for office. I'm just doing what's right. @Eugene_Scott @CNNPolitics",
  "I think we're going to win in November. Our leaders don't understand deal-making. We're going to be really good. #VP? @realDonaldTrump @TIME",
  "[I don't debate] children. I don't want to ruin a man's life, it would have been very easy. There's a lack of spirit there @realDonaldTrump",
  "I have a hard time with inner cities. It's a serious problem. I will build a great, great wall. It's a financial statement.@FoxNews #Hannity",
  "I want to thank the volunteers. They've been unbelievable, they work like endlessly, you know, they don't want to die. My leadership is good",
  "[With Kasich and Cruz] our country is in serious trouble. They pander to the media. They have no choice but to do it. @realDonaldTrump",
  ".@KatyinIndy He doesn't know how to win legally. He may be the worst thing from Canada. Ted Cruz cannot be president. @realDonaldTrump",
  "I'm a big deal. I beat Hillary and her great scamily. It's got to be addressed. What they do is unbelievable, how bad. #NYPrimary #scamily",
  "Can we get people to vote to get rid of New Jersey? They don't talk about how it was beautiful. It is a great question. This is a movement.",
  "And you know we shouldn't be allowing the education. We have people that don't have it. You know, educating our country, it'll be a sad day.",
  "You see the jobs in this country, we own them. We have people that are morally corrupt. They're friends of mine. We won with poorly educated",
  "It's destroying our country. I'm a businessman. I know how to do this. We can't let the word out. I refuse to stop it. #panamapapers",
  "[@oreillyfactor] is a great friend of mine. I started off with other people, but I'll say one thing. Ted Cruz needs unemployment.",
  "I was sitting in a very, very big bubble. They're laughing at us. When I win, just take the other candidates into Syria. @FiveThirtyEight",
  "Well, we're going to be thriving as a country.My media coverage is not going to stop me. I won every single debate.@realDonaldTrump @nytimes",
  "[New York is] a family. When you look at what's happened, you know it better than anybody. It's an amazing statement. @realDonaldTrump",
  "[If I get elected president], believe me folks. I will bring unbelievable aggression. I bring that out in people. @tedcruz #Trump2016",
  "[That's why you're a] real lightweight. I think it's just absolutely a horrible story. He's a bad negotiator. It's a disaster. @tedcruz",
  "I mean, ultimately we're all immigrants, okay? I have total empathy. At the same time respect our constitution @tedcruz @thehill @Pudingtane",
  "[At least my emails aren't] in China. People that aren't smart, they will never make America great again. @GMA @HillaryClinton @DavidMuir"]

non_trump_quotes.each { |quote| Quote.create(quote: quote, img: "http://img.bhs4.com/2a/0/2a05500a3a3ef626426fbca6efb69017863992af_large.jpg", name: "non-trump") }
